version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: becode
    ports:
      - 8080:80
    volumes:
      - .:/srv/app
    links:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - mysql:mysql
      ports:
        - 9191:80
      environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: pw
        PMA_HOST: mysql